### ISSUE TITLE
pvrsrvkm.so error

### ISSUE THREAD

**Issue by jekenpwn** [renesas-rcar/linux-bsp#1]
Hi 
I met a issue throw by pvrsrvkm.so with RcarE3
I am not any idea about these error log, could you give me some idea?
When I run my Kanzi application, it will be crashed after a bit time, and error log like below:
`
[  468.693594] PVR_K:  1050414464: ------[ Driver Info ]------
[  468.699241] PVR_K:  1050414464: UM info: 1.10 @  5187610 (release) build options: 0x80000810
[  468.708983] PVR_K:  1050414464: KM info: 1.10 @  5187610 (release) build options: 0x00000810
[  468.717623] PVR_K:  1050414464: FW info: 1.10 @  5187610 (release) build options: 0x80000810
[  468.726230] PVR_K:  1050414464: Comparison of UM/KM components: MATCHING
[  468.732974] PVR_K:  1050414464: KM Arch: 64 Bit
[  468.737577] PVR_K:  1050414464: UM Connected Clients: 64 Bit
[  468.743289] PVR_K:  1050414464: ------[ RGX summary ]------
[  468.748952] PVR_K:  1050414464: RGX BVNC: 22.67.54.30
[  468.754043] PVR_K:  1050414464: RGX Device State: Active
[  468.759435] PVR_K:  1050414464: RGX Power State: ON
[  468.764353] PVR_K:  1050414464: BIF0 - OK
[  468.768465] PVR_K:  1050414464: RGX FW State: OK (HWRState 0x00000001: HWR OK; )
[  468.775908] PVR_K:  1050414464: RGX FW Power State: RGXFWIF_POW_ON (APM disabled: 0 ok, 0 denied, 0 non-idle, 0 other, 0 total. Latency: 100 ms)
[  468.788946] PVR_K:  1050414464: RGX DVFS: 0 frequency changes. Current frequency: 599 MHz (sampled at 6b24fd8b4e)
[  468.799381] PVR_K:  1050414464: RGX FW OS 0 State: 0x00000001 (Active: Yes, Freelists: Not Ok, Grow Request Pending: No)
[  468.810378] PVR_K:  1050414464: Number of HWR: GP(0/0+0), 2D(0/0+0), TA(0/0+0), 3D(1/1+0), CDM(0/0+0), FALSE(0,0,0,0,0)
[  468.821210] PVR_K:  1050414464: DM 0 (GP)
[  468.825337] PVR_K:  1050414464: DM 1 (HWRflags 0x00000000: working; )
[  468.831828] PVR_K:  1050414464: DM 2 (HWRflags 0x00000000: working; )
[  468.838389] PVR_K:  1050414464: DM 3 (HWRflags 0x00000000: working; )
[  468.844877] PVR_K:  1050414464:   Recovery 1: PID = -32768, frame = 3043, HWRTData = 0xC0094300, EventStatus = 0x00000010, Guilty Lockup
[  468.857238] PVR_K:  1050414464:               CRTimer = 0x000040F2A8B3, OSTimer = 468.691915585, CyclesElapsed = 40126720
[  468.868251] PVR_K:  1050414464:               PreResetTimeInCycles = 50944, HWResetTimeInCycles = 62720, TotalRecoveryTimeInCycles = 113664
[  468.880860] PVR_K:  1050414464: DM 4 (HWRflags 0x00000000: working; )
[  468.887344] PVR_K:  1050414464: ------[ RGX registers ]------
[  468.893188] PVR_K:  1050414464: RGX Register Base Address (Linear):   0xffff00000ac40000
[  468.901323] PVR_K:  1050414464: RGX Register Base Address (Physical): 0xFD000000
[  468.908904] PVR_K:  1050414464: CORE_ID                       : 0x0000000008470000
[  468.916521] PVR_K:  1050414464: CORE_REVISION                 : 0x0036001E
[  468.923463] PVR_K:  1050414464: DESIGNER_REV_FIELD1           : 0x00000000
[  468.930378] PVR_K:  1050414464: DESIGNER_REV_FIELD2           : 0x00000000
[  468.937326] PVR_K:  1050414464: CHANGESET_NUMBER              : 0x0000000000000000
[  468.944950] PVR_K:  1050414464: CLK_CTRL                      : 0x002AAA002A2AAAAA
[  468.952589] PVR_K:  1050414464: CLK_STATUS                    : 0x0000000000600000
[  468.960195] PVR_K:  1050414464: CLK_CTRL2                     : 0x0000000000000000
[  468.967833] PVR_K:  1050414464: CLK_STATUS2                   : 0x0000000000000000
[  468.975440] PVR_K:  1050414464: EVENT_STATUS                  : 0x00000010
[  468.982391] PVR_K:  1050414464: TIMER                         : 0x0000000040FCFE86
[  468.990003] PVR_K:  1050414464: BIF_FAULT_BANK0_MMU_STATUS    : 0x00000000
[  468.996967] PVR_K:  1050414464: BIF_FAULT_BANK0_REQ_STATUS    : 0x0000000000000000
[  469.004573] PVR_K:  1050414464: BIF_FAULT_BANK1_MMU_STATUS    : 0x00000000
[  469.011535] PVR_K:  1050414464: BIF_FAULT_BANK1_REQ_STATUS    : 0x0000000000000000
[  469.019151] PVR_K:  1050414464: BIF_MMU_STATUS                : 0x00000000
[  469.026091] PVR_K:  1050414464: BIF_MMU_ENTRY                 : 0x00000000
[  469.033010] PVR_K:  1050414464: BIF_MMU_ENTRY_STATUS          : 0x0000000000000000
[  469.040655] PVR_K:  1050414464: BIF_STATUS_MMU                : 0x00000000
[  469.047585] PVR_K:  1050414464: BIF_READS_EXT_STATUS          : 0x00000000
[  469.054527] PVR_K:  1050414464: BIF_READS_INT_STATUS          : 0x00000000
[  469.061446] PVR_K:  1050414464: BIFPM_STATUS_MMU              : 0x00000000
[  469.068395] PVR_K:  1050414464: BIFPM_READS_EXT_STATUS        : 0x00000000
[  469.075320] PVR_K:  1050414464: BIFPM_READS_INT_STATUS        : 0x00000000
[  469.082260] PVR_K:  1050414464: Warning: BRN44871 is present
[  469.087960] PVR_K:  1050414464: BIF_CAT_BASE_INDEX            : 0x0000000000000303
[  469.095603] PVR_K:  1050414464: BIF_CAT_BASE0                 : 0x0000000000000000
[  469.103232] PVR_K:  1050414464: BIF_CAT_BASE1                 : 0x000000007A0F8000
[  469.110887] PVR_K:  1050414464: BIF_CAT_BASE2                 : 0x000000007A27B000
[  469.118503] PVR_K:  1050414464: BIF_CAT_BASE3                 : 0x000000007A363000
[  469.126140] PVR_K:  1050414464: BIF_CAT_BASE4                 : 0x0000000000000000
[  469.133752] PVR_K:  1050414464: BIF_CAT_BASE5                 : 0x0000000000000000
[  469.141390] PVR_K:  1050414464: BIF_CAT_BASE6                 : 0x0000000000000000
[  469.149013] PVR_K:  1050414464: BIF_CAT_BASE7                 : 0x0000000000000000
[  469.156655] PVR_K:  1050414464: BIF_CTRL_INVAL                : 0x00000000
[  469.163570] PVR_K:  1050414464: BIF_CTRL                      : 0x000000C0
[  469.170511] PVR_K:  1050414464: BIF_PM_CAT_BASE_VCE0          : 0x0000000000000000
[  469.178119] PVR_K:  1050414464: BIF_PM_CAT_BASE_TE0           : 0x0000000000000000
[  469.185756] PVR_K:  1050414464: BIF_PM_CAT_BASE_ALIST0        : 0x0000000000000000
[  469.193371] PVR_K:  1050414464: BIF_PM_CAT_BASE_VCE1          : 0x0000000000000000
[  469.201014] PVR_K:  1050414464: BIF_PM_CAT_BASE_TE1           : 0x0000000000000000
[  469.208637] PVR_K:  1050414464: BIF_PM_CAT_BASE_ALIST1        : 0x0000000000000000
[  469.216278] PVR_K:  1050414464: PERF_TA_PHASE                 : 0x00000000
[  469.223196] PVR_K:  1050414464: PERF_TA_CYCLE                 : 0x00000000
[  469.230137] PVR_K:  1050414464: PERF_3D_PHASE                 : 0x00000000
[  469.237054] PVR_K:  1050414464: PERF_3D_CYCLE                 : 0x00000000
[  469.244016] PVR_K:  1050414464: PERF_TA_OR_3D_CYCLE           : 0x00000000
[  469.251121] PVR_K:  1050414464: PERF_TA_AND_3D_CYCLE          : 0x00000000
[  469.258078] PVR_K:  1050414464: PERF_COMPUTE_PHASE            : 0x00000000
[  469.265038] PVR_K:  1050414464: PERF_COMPUTE_CYCLE            : 0x00000000
[  469.271959] PVR_K:  1050414464: PM_PARTIAL_RENDER_ENABLE      : 0x00000000
[  469.278905] PVR_K:  1050414464: ISP_RENDER                    : 0x00000000
[  469.285825] PVR_K:  1050414464: TLA_STATUS                    : 0x0000000000000000
[  469.293460] PVR_K:  1050414464: MCU_FENCE                     : 0x0000000000000000
[  469.301082] PVR_K:  1050414464: VDM_CONTEXT_STORE_STATUS      : 0x00000001
[  469.308021] PVR_K:  1050414464: VDM_CONTEXT_STORE_TASK0       : 0x0000000000000000
[  469.315677] PVR_K:  1050414464: VDM_CONTEXT_STORE_TASK1       : 0x0000000000000000
[  469.323340] PVR_K:  1050414464: VDM_CONTEXT_STORE_TASK2       : 0x0000000000000000
[  469.330973] PVR_K:  1050414464: VDM_CONTEXT_RESUME_TASK0      : 0x0000000000000000
[  469.338612] PVR_K:  1050414464: VDM_CONTEXT_RESUME_TASK1      : 0x0000000000000000
[  469.346223] PVR_K:  1050414464: VDM_CONTEXT_RESUME_TASK2      : 0x0000000000000000
[  469.353850] PVR_K:  1050414464: ISP_CTL                       : 0x00000000
[  469.360771] PVR_K:  1050414464: ISP_STATUS                    : 0x00000000
[  469.367710] PVR_K:  1050414464: MTS_INTCTX                    : 0x00000000
[  469.374636] PVR_K:  1050414464: MTS_BGCTX                     : 0x00000000
[  469.381575] PVR_K:  1050414464: MTS_BGCTX_COUNTED_SCHEDULE    : 0x00000000
[  469.388493] PVR_K:  1050414464: MTS_SCHEDULE                  : 0x00000000
[  469.395452] PVR_K:  1050414464: MTS_GPU_INT_STATUS            : 0x00004110
[  469.402363] PVR_K:  1050414464: CDM_CONTEXT_STORE_STATUS      : 0x00000000
[  469.409307] PVR_K:  1050414464: CDM_CONTEXT_PDS0              : 0x0000000000000000
[  469.416932] PVR_K:  1050414464: CDM_CONTEXT_PDS1              : 0x0000000000000000
[  469.424576] PVR_K:  1050414464: CDM_TERMINATE_PDS             : 0x0000000000000000
[  469.432191] PVR_K:  1050414464: CDM_TERMINATE_PDS1            : 0x0000000000000000
[  469.439827] PVR_K:  1050414464: SIDEKICK_IDLE                 : 0x0000007E
[  469.446742] PVR_K:  1050414464: SLC_IDLE                      : 0x000000FF
[  469.453679] PVR_K:  1050414464: SLC_STATUS0                   : 0x00000000
[  469.460597] PVR_K:  1050414464: SLC_STATUS1                   : 0x0000000000000000
[  469.468254] PVR_K:  1050414464: SLC_STATUS2                   : 0x0000000000000000
[  469.475868] PVR_K:  1050414464: SLC_CTRL_BYPASS               : 0x01000000
[  469.482808] PVR_K:  1050414464: SLC_CTRL_MISC                 : 0x0000000000200003
[  469.490419] PVR_K:  1050414464: MIPS_ADDR_REMAP1_CONFIG1      : 0x1FC00001
[  469.497368] PVR_K:  1050414464: MIPS_ADDR_REMAP1_CONFIG2      : 0x000000007A16100C
[  469.504994] PVR_K:  1050414464: MIPS_ADDR_REMAP2_CONFIG1      : 0x1FC01001
[  469.511939] PVR_K:  1050414464: MIPS_ADDR_REMAP2_CONFIG2      : 0x000000007A16900C
[  469.519547] PVR_K:  1050414464: MIPS_ADDR_REMAP3_CONFIG1      : 0x1FC02001
[  469.526489] PVR_K:  1050414464: MIPS_ADDR_REMAP3_CONFIG2      : 0x000000007A16000C
[  469.534103] PVR_K:  1050414464: MIPS_ADDR_REMAP4_CONFIG1      : 0x7A174001
[  469.541055] PVR_K:  1050414464: MIPS_ADDR_REMAP4_CONFIG2      : 0x000000001FC0000E
[  469.548667] PVR_K:  1050414464: MIPS_ADDR_REMAP5_CONFIG1      : 0x00000001
[  469.555604] PVR_K:  1050414464: MIPS_ADDR_REMAP5_CONFIG2      : 0x000000007A16100C
[  469.563216] PVR_K:  1050414464: MIPS_WRAPPER_CONFIG           : 0x000000000001FD00
[  469.570853] PVR_K:  1050414464: MIPS_EXCEPTION_STATUS         : 0x00000020
[  469.577937] PVR_K:  1050414464: ---- [ MIPS internal state ] ----
[  469.584116] PVR_K:  1050414464: PC                            : 0xC0019972
[  469.591061] PVR_K:  1050414464: STATUS_REGISTER               : 0x00481C05
[  469.597978] PVR_K:  1050414464: CAUSE_REGISTER                : 0x00800000
[  469.604931] PVR_K:  1050414464: BAD_REGISTER                  : 0xC0019972
[  469.611848] PVR_K:  1050414464: EPC                           : 0xC0019976
[  469.618784] PVR_K:  1050414464: SP                            : 0xCF600FE0
[  469.625700] PVR_K:  1050414464: BAD_INSTRUCTION               : 0x00000000
[  469.632645] PVR_K:  1050414464: TLB                           :
[  469.638615] PVR_K:  1050414464:  0) VA 0xCF400000 ( 64k) -> PA0 0xFD000000 DV  , PA1 0x00000000    C
[  469.647823] PVR_K:  1050414464:  1) VA 0xCF000000 ( 16k) -> PA0 0x7A130000 DVGC, PA1 0x7A134000 DVGC
[  469.657004] PVR_K:  1050414464:  2) VA 0xCF600000 (  4k) -> PA0 0x7A16A000 DV C, PA1 0x00000000    C
[  469.666216] PVR_K:  1050414464:  3) VA 0xC000A000 (  4k) -> PA0 0x7A12E000 DVGC, PA1 0x7A12F000 DVGC
[  469.675397] PVR_K:  1050414464:  4) VA 0xC0010000 (  4k) -> PA0 0x7A144000 DVGC, PA1 0x7A145000 DVGC
[  469.684599] PVR_K:  1050414464:  5) VA 0xC0018000 (  4k) -> PA0 0x7A14C000 DVGC, PA1 0x7A14D000 DVGC
[  469.693783] PVR_K:  1050414464:  6) VA 0xC0094000 (  4k) -> PA0 0x6FE28000 DVGC, PA1 0x72145000 DVG
[  469.702989] PVR_K:  1050414464:  7) VA 0xC0048000 (  4k) -> PA0 0x7A185000 DVG , PA1 0x7A186000 DVG
[  469.712172] PVR_K:  1050414464:  8) VA 0xC0008000 (  4k) -> PA0 0x7A12C000 DVGC, PA1 0x7A12D000 DVGC
[  469.721378] PVR_K:  1050414464:  9) VA 0xC007A000 (  4k) -> PA0 0x7CD9B000 DVGC, PA1 0x7B090000 DVGC
[  469.730561] PVR_K:  1050414464: 10) VA 0xC000C000 (  4k) -> PA0 0x7A140000 DVGC, PA1 0x7A141000 DVGC
[  469.739759] PVR_K:  1050414464: 11) VA 0xC0050000 (  4k) -> PA0 0x7A0DF000 DVGC, PA1 0x7A0DD000 DVG
[  469.748942] PVR_K:  1050414464: 12) VA 0xC008A000 (  4k) -> PA0 0x71E4C000 DVGC, PA1 0x738F7000 DVGC
[  469.758152] PVR_K:  1050414464: 13) VA 0xC002E000 (  4k) -> PA0 0x7A162000 DVGC, PA1 0x7A163000 DVGC
[  469.767335] PVR_K:  1050414464: 14) VA 0xC0040000 (  4k) -> PA0 0x7A17B000 DVG , PA1 0x7A17C000 DVG
[  469.776535] PVR_K:  1050414464: 15) VA 0xC0004000 (  4k) -> PA0 0x7A128000 DVGC, PA1 0x7A129000 DVGC
[  469.785720] PVR_K:  1050414464: --------------------------------
[  469.791786] PVR_K:  1050414464: RGX Kernel CCB WO:0x7F RO:0x7F
[  469.797659] PVR_K:  1050414464: RGX Firmware CCB WO:0x1F RO:0x1D
[  469.803726] PVR_K:  1050414464: RGX Kernel CCB commands executed = 55295
[  469.810477] PVR_K:  1050414464: RGX FW thread 0: FW IRQ count = 52832, Last sampled IRQ count in LISR = 52832
[  469.820471] PVR_K:  1050414464: FW OS config flags = 0x800127 (Ctx switch: TA; 3D; CDM; VDM CS INDEX mode; Medium CSW profile; Use extended; HWR EN; )
[  469.834044] PVR_K:  1050414464: Debug log type: none
[  469.839077] PVR_K:  1050414464: RGX FW thread 0: Trace buffer not yet allocated
[  469.846430] PVR_K:  1050414464: ------[ Stalled FWCtxs ]------
[  469.852345] PVR_K:  1050414464: FWCtx 0xC004E1A0 @ 6592 (3D-P4294934528-T990252416-aun) pending on FENCE_PR:
[  469.862222] PVR_K:  1050414464:   Addr:0xc0051050  Value=0x00001807
[  469.868556] PVR_K:  1050414464:  FWCtx 0xC004E1A0 fenced command is of type 3D_PR
[  469.876098] PVR_K:  1050414464: FWCtx 0xC004EB80 @ 18856 (TA-P4294934528-T1032140288-er) pending on FENCE:
[  469.885831] PVR_K:  1050414464:   Addr:0xc0095041  Value=0x00000519
[  469.892143] PVR_K:  1050414464:  FWCtx 0xC004EB80 fenced command is of type TA
[  469.899432] PVR_K:  1050414464:  preventing UPDATE:
[  469.904348] PVR_K:  1050414464:   Addr:0xc00751c8  Value=0x00000777
[  469.910676] PVR_K:  1050414464:   Addr:0xc0075204  Value=0x000011a9
[  469.916985] PVR_K:  1050414464:   Addr:0xc008e000  Value=0x00007cd4
[  469.923319] PVR_K:  1050414464:   Addr:0xc008e004  Value=0x0002c470
[  469.929628] PVR_K:  1050414464:   Addr:0xc008e008  Value=0x00000000
[  469.935958] PVR_K:  1050414464:   Addr:0xc008e00c  Value=0x00016154
[  469.942271] PVR_K:  1050414464:   Addr:0xc008e010  Value=0x000161f0
[  469.948594] PVR_K:  1050414464:   Addr:0xc008e014  Value=0x00000000
[  469.954946] PVR_K:  1050414464: ------[ Debug summary ]------
[  469.960785] PVR_K:  1050414464: BIF0 - OK
[  469.964838] PVR_K:  1050414464: RGX FW State: OK (HWRState 0x00000001: HWR OK; )
[  469.972304] PVR_K:  1050414464: RGX FW Power State: RGXFWIF_POW_IDLE (APM disabled: 0 ok, 0 denied, 0 non-idle, 0 other, 0 total. Latency: 100 ms)
[  469.985500] PVR_K:  1050414464: RGX DVFS: 0 frequency changes. Current frequency: 599 MHz (sampled at 6b24fd8b4e)
[  469.995827] PVR_K:  1050414464: RGX FW OS 0 State: 0x00000001 (Active: Yes, Freelists: Not Ok, Grow Request Pending: No)
[  470.006778] PVR_K:  1050414464: Number of HWR: GP(0/0+0), 2D(0/0+0), TA(0/0+0), 3D(1/1+0), CDM(0/0+0), FALSE(0,0,0,0,0)
[  470.017641] PVR_K:  1050414464: DM 0 (GP)
[  470.021702] PVR_K:  1050414464: DM 1 (HWRflags 0x00000000: working; )
[  470.028230] PVR_K:  1050414464: DM 2 (HWRflags 0x00000000: working; )
[  470.034719] PVR_K:  1050414464: DM 3 (HWRflags 0x00000000: working; )
[  470.041241] PVR_K:  1050414464:   Recovery 1: PID = -32768, frame = 3043, HWRTData = 0xC0094300, EventStatus = 0x00000010, Guilty Lockup
[  470.053559] PVR_K:  1050414464:               CRTimer = 0x000040F2A8B3, OSTimer = 468.691915585, CyclesElapsed = 40126720
[  470.064589] PVR_K:  1050414464:               PreResetTimeInCycles = 50944, HWResetTimeInCycles = 62720, TotalRecoveryTimeInCycles = 113664
[  470.077172] PVR_K:  1050414464: DM 4 (HWRflags 0x00000000: working; )
[  470.083779] ------------[ cut here ]------------
[  470.088930] WARNING: CPU: 1 PID: 20 at /home/jeken/hdddisk_1T/hdd_working/MM_Project/Yocto-3.21/WORK/E3/tmp/work/ebisu-poky-linux/kernel-module-gles/1.0-r0/rogue_km/binary_r8a7799_linux_release/target_aarch64/kbuild/services/server/devices/rgx/rgxfwutils.c:4326 RGXCheckFirmwareCCB+0x2d8/0x4f0 [pvrsrvkm]
[  470.115831] Modules linked in: vsp2(O) vspm(O) pvrsrvkm(O) ipv6
[  470.121784] CPU: 1 PID: 20 Comm: kworker/u4:1 Tainted: G      D    O    4.14.75-ltsi-yocto-standard #8
[  470.131104] Hardware name: Renesas Ebisu board based on r8a77990 ES1.0 (DT)
[  470.138542] Workqueue: pvr_misr MISRWrapper [pvrsrvkm]
[  470.143692] task: ffff80003ea51b00 task.stack: ffff000008cd8000
[  470.150067] PC is at RGXCheckFirmwareCCB+0x2d8/0x4f0 [pvrsrvkm]
[  470.156448] LR is at RGXCheckFirmwareCCB+0x2d8/0x4f0 [pvrsrvkm]
[  470.162378] pc : [<ffff0000007a5470>] lr : [<ffff0000007a5470>] pstate: 60000145
[  470.169783] sp : ffff000008cdbca0
[  470.173100] x29: ffff000008cdbca0 x28: ffff00000b063040
[  470.178422] x27: ffff00000b063420 x26: 00000000000003a0
[  470.183742] x25: ffff00000084e680 x24: ffff00000084d5c8
[  470.189063] x23: ffff000000805c98 x22: 0000000070014008
[  470.194383] x21: ffff00000086add0 x20: ffff80003d88b000
[  470.199704] x19: ffff00000b063080 x18: 000000000000000a
[  470.205024] x17: 0000000000006030 x16: 0000000000003800
[  470.210345] x15: 0000000000012d74 x14: ffff000088a9631f
[  470.215665] x13: ffffffffffffffff x12: 0000000000000030
[  470.220985] x11: 00000000fffffffe x10: ffff000008a296f8
[  470.226306] x9 : 000000000000000c x8 : ffff000008a296f0
[  470.231626] x7 : 0000000000000000 x6 : 0000000000000000
[  470.236946] x5 : 0000000000000000 x4 : 0000000000000000
[  470.242267] x3 : ffff80003ea51b00 x2 : 0000000000000000
[  470.247587] x1 : ffff80003ea51b00 x0 : ffff80003cd48300
[  470.252909] Call trace:
[  470.255361] Exception stack(0xffff000008cdbb60 to 0xffff000008cdbca0)
[  470.261813] bb60: ffff80003cd48300 ffff80003ea51b00 0000000000000000 ffff80003ea51b00
[  470.269656] bb80: 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[  470.277498] bba0: ffff000008a296f0 000000000000000c ffff000008a296f8 00000000fffffffe
[  470.285340] bbc0: 0000000000000030 ffffffffffffffff ffff000088a9631f 0000000000012d74
[  470.293183] bbe0: 0000000000003800 0000000000006030 000000000000000a ffff00000b063080
[  470.301026] bc00: ffff80003d88b000 ffff00000086add0 0000000070014008 ffff000000805c98
[  470.308869] bc20: ffff00000084d5c8 ffff00000084e680 00000000000003a0 ffff00000b063420
[  470.316712] bc40: ffff00000b063040 ffff000008cdbca0 ffff0000007a5470 ffff000008cdbca0
[  470.324554] bc60: ffff0000007a5470 0000000060000145 ffff000008cdbca0 ffff0000007a5470
[  470.332397] bc80: ffffffffffffffff ffff80003d88b000 ffff000008cdbca0 ffff0000007a5470
[  470.340691] [<ffff0000007a5470>] RGXCheckFirmwareCCB+0x2d8/0x4f0 [pvrsrvkm]
[  470.348106] [<ffff0000007a7700>] RGX_MISRHandler_Main+0x28/0x60 [pvrsrvkm]
[  470.355416] [<ffff0000007616a8>] MISRWrapper+0x18/0x20 [pvrsrvkm]
[  470.361537] [<ffff0000080bf7e8>] process_one_work+0x188/0x264
[  470.367297] [<ffff0000080c0544>] worker_thread+0x22c/0x318
[  470.372794] [<ffff0000080c4f08>] kthread+0x11c/0x12c
[  470.377771] [<ffff000008084c98>] ret_from_fork+0x10/0x18
[  470.383091] ---[ end trace 45147f66640e2a60 ]---
info:debug> ************** CLU_FPS_50.930462 470.397295 **************

info:debug> ************** CLU_FPS_45.217392 470.996906 **************

info:debug> ************** CLU_FPS_32.007759 472.013783 **************

info:debug> ************** CLU_FPS_29.940121 473.008345 **************

[  473.942514] audit: type=1701 audit(1569346237.240:4): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=1988 comm="kzb_player" exe="/appfs/kanzi/kzb_player" sig=4 res=1
Illegal instruction (core dumped)
`
BR
Jeken ZHUANG

**Comment by morisyun26** [comment]
Hi Jeken,

Do you use the correct device tree for E3?

In your log, it's showed "[ 470.131104] Hardware name: Renesas Ebisu board based on r8a77990 ES1.0 (DT)", looks like r8a77990-es10-ebisu.dts. 

But I found three more types in the kernel source. 
Depends on the board type and SoC version, you can choose compatible dts.

Regards,
Moris

**Comment by jekenpwn** [comment]
Hi Moris,
Thanks for your response. This issue have been solved, and the reason was DDR chip unstable. I got one new board from HW side, it was OK.
For DT file, yes, I missed SOC compatible to using right one, but it is OK, I used our DT file, and follow r8a77990-es10-ebsu.dts to create new one, so SOC compatible was still unchanged 

BR,
Jeken
